[build]
  command = "cd server && npm install && cd ../client && npm install && npm run build"
  publish = "client/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "nft"

[functions.api]
  node_bundler = "nft"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
